# Generated by Django 4.2.13 on 2025-09-30 21:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckupPhotoAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annotated_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="checkups/annotated"
                    ),
                ),
                (
                    "bbox",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=4
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[("tree", "Tree"), ("shrub", "Shrub")], max_length=16
                    ),
                ),
                (
                    "breed",
                    models.CharField(
                        choices=[
                            ("unknown", "Не определено"),
                            ("oak", "Дуб"),
                            ("ash", "Ясень"),
                            ("poplar", "Тополь"),
                            ("pine", "Сосна"),
                            ("birch", "Берёза"),
                            ("elm", "Вяз"),
                            ("maple", "Клён"),
                            ("spruce", "Ель"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("normal", "Нормальное"),
                            ("falling", "Заваливающееся"),
                            ("fallen", "Упавшее"),
                            ("emergency", "Аварийное"),
                            ("unsatisfactory", "Не удовлетворительное"),
                            ("stump", "Пенёк"),
                        ],
                        default="normal",
                        max_length=32,
                    ),
                ),
                ("is_dry", models.BooleanField(default=False)),
                ("percentage_dried", models.PositiveSmallIntegerField(default=0)),
                (
                    "artifacts",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("crack", "Трещина"),
                                ("hollow", "Дупло"),
                                ("bark_removed", "Содранная кора"),
                                ("roots_exposed", "Обнажены корни"),
                                ("fungi", "Грибы"),
                                ("rot", "Гниль"),
                                ("stem_damage", "Повреждение ствола"),
                                ("crown_damage", "Повреждение кроны"),
                                ("broken_branches", "Обломанные ветки"),
                                ("broken_trunk", "Сломанный ствол"),
                            ],
                            max_length=32,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "season",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("vegetative", "Вегетативный"),
                            ("non_vegetative", "Не вегетативный"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "photo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation",
                        to="core.checkupphoto",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CheckupPhotoObject",
        ),
    ]
