# Generated by Django 4.2.13 on 2025-09-30 21:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_checkupphotoannotation_delete_checkupphotoobject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkupphotoannotation",
            name="bbox",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), null=True, size=4
            ),
        ),
    ]
