# Generated by Django 4.2.13 on 2025-10-18 21:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_checkupphotoannotation_bbox"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistrictArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "coords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        help_text="Coordinates of two opposite corners: [x1, y1, x2, y2]",
                        size=4,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="checkup",
            name="plot",
        ),
        migrations.AddField(
            model_name="checkup",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkups",
                to="core.districtarea",
            ),
        ),
    ]
