# Generated by Django 4.2.13 on 2025-10-18 22:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_districtarea_remove_checkup_plot_checkup_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkupphoto",
            name="coords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                default=[],
                help_text="Coordinate: [x, y]",
                size=2,
            ),
            preserve_default=False,
        ),
    ]
