# Generated by Django 4.2.13 on 2025-10-18 22:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_checkupphoto_coords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkupphoto",
            name="coords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                blank=True,
                default=None,
                help_text="Coordinate: [x, y]",
                null=True,
                size=2,
            ),
        ),
    ]
