# Generated by Django 4.2.13 on 2025-10-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_checkupphoto_coords"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkupphotoannotation",
            name="is_tree_finded",
            field=models.BooleanField(default=False),
        ),
    ]
